spring:
  application:
    name: customer-service

server:
  port: 8081
  servlet:
    context-path: /ad2

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/